### ISSUE TITLE
react-rsc / dev mode / fails require react-server-dom-vite-server

### ISSUE THREAD

**Issue by aheissenberger** [nksaraf/vinxi#181]
based on code from `test/templates/react-rsc`

1. start with `pnpm dev` 
2. open website with http://localhost:3000/

There app ist working in the browser and does update the conter on the server.

The problem is related to this file:
`node_modules/@vinxi/react-server-dom/server.node.js`

**output terminal:**
```
pnpm dev

> vinxi-tutorial@1.0.0 dev /TST/vinxi-tutorial
> vinxi dev

vinxi 0.2.1
vinxi starting dev server

  ➜ Local:    http://localhost:3000/
  ➜ Network:  use --host to expose

vinxi initializing rsc router worker
vinxi hook app:config-resolved
vinxi hook app:created
vinxi hook app:dev:start
vinxi hook app:dev:nitro:config
vinxi hook app:dev:server:created
[AsyncFunction: sayHello]
18:17:10 [vite] Error when evaluating SSR module @vinxi/react-server-dom/server:
|- ReferenceError: module is not defined
    at eval (/TST/vinxi-tutorial/node_modules/.pnpm/@vinxi+react-server-dom@0.0.3_react-dom@0.0.0-experimental-035a41c4e-20230704_react@0.0.0-exp_cqa2bnwrfhrn4c44xrhb26chtm/node_modules/@vinxi/react-server-dom/server.node.js:8:3)
    at instantiateModule (file:///TST/vinxi-tutorial/node_modules/.pnpm/vite@4.5.0/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:56052:15)

ReferenceError: module is not defined
    at eval (/TST/vinxi-tutorial/node_modules/.pnpm/@vinxi+react-server-dom@0.0.3_react-dom@0.0.0-experimental-035a41c4e-20230704_react@0.0.0-exp_cqa2bnwrfhrn4c44xrhb26chtm/node_modules/@vinxi/react-server-dom/server.node.js:8:3)
    at instantiateModule (file:///TST/vinxi-tutorial/node_modules/.pnpm/vite@4.5.0/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:56052:15)
```

**Comment by nksaraf** [comment]
this is not really a problem. Like u must have observed, it works in dev and prod too probably (without the console error during prod).

This error is unrelated , caused by an internal check in vinxi where I am not able to suppress these useless logs.
