### ISSUE TITLE
Uncaught Error when using createError 

### ISSUE THREAD

**Issue by madaxen86** [nksaraf/vinxi#190]
In a Solid-Start app (probably in any app) when using the createError function the browser logs the following error:
```
__vite-browser-external:node:async_hooks:3 Uncaught Error: Module "node:async_hooks" has been externalized for browser compatibility. Cannot access "node:async_hooks.AsyncLocalStorage" in client code.  See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
    at Object.get (__vite-browser-external:node:async_hooks:3:11)
    at http.js:109:53
```

Minimal example in a routes/index.tsx 
...
`const Error = () => createError({ message: "Error" })`
...

Weird thing is, that it is only logged as an error in the browser. Solid / node don't get the error. But it breaks Solid's lifecycle primitives (onMount, createEffect,...)

**Comment by nksaraf** [comment]
`createError` from '`vinxi/http`' or any server module is not meant to be used in the browser. It will error if you do.
