### ISSUE TITLE
test/react-rsc: failed to import "react"

### ISSUE THREAD

**Issue by aheissenberger** [nksaraf/vinxi#194]
This error exists only with `pnpm dev` with `examples/react/rsc/spa`  and `test/templates/react-rsc`.

How can I fix this problem?

```
react-rsc % pnpm dev

> test-react-rsc@ dev /vinxi/test/templates/react-rsc
> vinxi dev

vinxi 0.3.3
vinxi starting dev server

  ➜ Local:    http://localhost:3000/
  ➜ Network:  use --host to expose

vinxi initializing rsc router worker
vinxi hook app:config-resolved
vinxi hook app:created
vinxi hook app:dev:start
vinxi hook app:dev:nitro:config
vinxi hook app:dev:server:created
12:24:01 AM [vite] Error when evaluating SSR module /@fs/vinxi/packages/vinxi-react/lazy-route.js: failed to import "react"
|- SyntaxError: [vite] Named export 'useLayoutEffect' not found. The requested module 'react' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'react';
const {useLayoutEffect} = pkg;

    at analyzeImportedModDifference (file:///vinxi/node_modules/.pnpm/vite@5.1.1_@types+node@18.18.8/node_modules/vite/dist/node/chunks/dep-94_H5fT6.js:54798:19)
    at nodeImport (file:///vinxi/node_modules/.pnpm/vite@5.1.1_@types+node@18.18.8/node_modules/vite/dist/node/chunks/dep-94_H5fT6.js:54749:9)
    at async ssrImport (file:///vinxi/node_modules/.pnpm/vite@5.1.1_@types+node@18.18.8/node_modules/vite/dist/node/chunks/dep-94_H5fT6.js:54644:24)
    at async eval (/vinxi/packages/vinxi-react/lazy-route.js:3:44)
    at async instantiateModule (file:///vinxi/node_modules/.pnpm/vite@5.1.1_@types+node@18.18.8/node_modules/vite/dist/node/chunks/dep-94_H5fT6.js:54706:9)
```

**Comment by nksaraf** [comment]
this is in a cloned repo? Shouldnt happen in the repo. Can happen outside

**Comment by aheissenberger** [comment]
I have this error in my own application which I build by copying parts of the examples and in the original cloned repo.


```
node -v
v21.6.1
```

This is what I did with the cloned repo:
```sh
git clone git@github.com:nksaraf/vinxi.git
cd vinxi
git rev-parse HEAD # 9ef80532ff916b59c867c20e7776044e80039e44
pnpm i
cd examples/react/rsc/spa
pnpm dev
```

**Error:** 
```
> test-react-rsc@ dev /vinxi/test/templates/react-rsc
> vinxi dev

vinxi 0.3.3
vinxi starting dev server

  ➜ Local:    http://localhost:3000/
  ➜ Network:  use --host to expose

vinxi initializing rsc router worker
vinxi hook app:config-resolved
vinxi hook app:created
vinxi hook app:dev:start
vinxi hook app:dev:nitro:config
vinxi hook app:dev:server:created
12:24:01 AM [vite] Error when evaluating SSR module /@fs/vinxi/packages/vinxi-react/lazy-route.js: failed to import "react"
|- SyntaxError: [vite] Named export 'useLayoutEffect' not found. The requested module 'react' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'react';
const {useLayoutEffect} = pkg;

    at analyzeImportedModDifference (file:///vinxi/node_modules/.pnpm/vite@5.1.1_@types+node@18.18.8/node_modules/vite/dist/node/chunks/dep-94_H5fT6.js:54798:19)
    at nodeImport (file:///vinxi/node_modules/.pnpm/vite@5.1.1_@types+node@18.18.8/node_modules/vite/dist/node/chunks/dep-94_H5fT6.js:54749:9)
    at async ssrImport (file:///vinxi/node_modules/.pnpm/vite@5.1.1_@types+node@18.18.8/node_modules/vite/dist/node/chunks/dep-94_H5fT6.js:54644:24)
    at async eval (/vinxi/packages/vinxi-react/lazy-route.js:3:44)
    at async instantiateModule (file:///vinxi/node_modules/.pnpm/vite@5.1.1_@types+node@18.18.8/node_modules/vite/dist/node/chunks/dep-94_H5fT6.js:54706:9)
```

**Comment by aheissenberger** [comment]
I also cloned the repo into a volumn which is based on your devContainer setting (e.g. Node v10.10.0) - still the same Error when using `pnpm dev`

**Comment by nksaraf** [comment]
Can you show a full repro ( a github repo preferably or stackblitz) so I can try it out and fix the issue?

**Comment by aheissenberger** [comment]
Hi Nikhil,
thank you for your time - here is a stack biz: https://stackblitz.com/~/github.com/aheissenberger/vinxi-react-rsc
or on GitHub: https://github.com/aheissenberger/vinxi-react-rsc.git

This is a 1:1 copy of the code from your repo `test/templates/react-rsc` - I get the same error when testing the same code directly in your repo.

open the terminal on stack biz and type `pnpm dev`, than load the page http://localhost:3000 :
```
vinxi initializing rsc router worker
vinxi hook app:config-resolved
vinxi hook app:created
vinxi hook app:dev:start
vinxi hook app:dev:nitro:config
vinxi hook app:dev:server:created
04:31:06 [vite] Error when evaluating SSR module /node_modules/.pnpm/@vinxi+react@0.2.0/node_modules/@vinxi/react/lazy-route.js: failed to import "react"
|- SyntaxError: [vite] Named export 'useLayoutEffect' not found. The requested module 'react' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'react';
const {useLayoutEffect} = pkg;

    at analyzeImportedModDifference (file:///home/aheissenberger/vinxi-react-rsc/node_modules/.pnpm/vite@5.1.1/node_modules/vite/dist/node/chunks/dep-94_H5fT6.js:54847:19)
    at nodeImport (file:///home/aheissenberger/vinxi-react-rsc/node_modules/.pnpm/vite@5.1.1/node_modules/vite/dist/node/chunks/dep-94_H5fT6.js:54798:9)
    at async ssrImport (file:///home/aheissenberger/vinxi-react-rsc/node_modules/.pnpm/vite@5.1.1/node_modules/vite/dist/node/chunks/dep-94_H5fT6.js:54693:24)
    at async eval (/home/aheissenberger/vinxi-react-rsc/node_modules/.pnpm/@vinxi+react@0.2.0/node_modules/@vinxi/react/lazy-route.js:3:44)
    at async instantiateModule (file:///home/aheissenberger/vinxi-react-rsc/node_modules/.pnpm/vite@5.1.1/node_modules/vite/dist/node/chunks/dep-94_H5fT6.js:54755:9)
```

**Comment by nksaraf** [comment]
Okay try the latest example. `react/rsc/spa`. I fixed all the bugs, should be fixed now
