### ISSUE TITLE
Path aliases not working anymore [0.2.1->0.3.0]

### ISSUE THREAD

**Issue by simonedelmann** [nksaraf/vinxi#200]
I am using path aliases as shown in the docs. After updating vinxi from 0.2.1 -> 0.3.0, path aliases stopped working and vite throws an error:
```
Error: The following dependencies are imported but could not be resolved:

  @/components/login (imported by /Users/simon/dev/philharmonic/app/main.tsx)
  @/components/notifications (imported by /Users/simon/dev/philharmonic/app/main.tsx)
  @/routeTree.gen (imported by /Users/simon/dev/philharmonic/app/main.tsx)
  @/utils/api (imported by /Users/simon/dev/philharmonic/app/main.tsx)

Are they installed?
    at file:///Users/simon/dev/philharmonic/node_modules/vinxi/node_modules/vite/dist/node/chunks/dep-94_H5fT6.js:52251:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///Users/simon/dev/philharmonic/node_modules/vinxi/node_modules/vite/dist/node/chunks/dep-94_H5fT6.js:51663:38
```

My `app.config.ts`:
```ts
import react from '@vitejs/plugin-react-swc'
import { createApp } from 'vinxi'
import viteTsconfigPaths from 'vite-tsconfig-paths'

export default createApp({
  routers: [
    {
      name: 'server',
      target: 'server',
      type: 'http',
      base: '/trpc',
      handler: './server/index.ts',
    },

    {
      name: 'client',
      target: 'browser',
      type: 'spa',
      handler: 'index.html',
      plugins: () => [
        viteTsconfigPaths(),
        react(),
      ],
    },
  ],
})
```

**Comment by nksaraf** [comment]
Can you show a full repro so I can try it out and fix the issue?

**Comment by simonedelmann** [comment]
I am very sorry! I made a reproduction and tested various things. In the end I solved it myself: I was missing the `viteTsconfigPaths()` on the (server) http handler. 

This is working now:
```ts
export default createApp({
  routers: [
    {
      name: 'server',
      target: 'server',
      type: 'http',
      base: '/trpc',
      handler: './server/index.ts',
      plugins: () => [viteTsconfigPaths()], // Added this line
    },

    {
      name: 'client',
      target: 'browser',
      type: 'spa',
      handler: 'index.html',
      plugins: () => [
        viteTsconfigPaths(),
        react(),
      ],
    },
  ],
})
```
For some reason this was not required prior to 0.3.0.
