### ISSUE TITLE
Error: Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by semiautomatix** [nksaraf/vinxi#208]
It seems it's not possible to set the session at present in my solid-start project.

All request are returning:

```
Error: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (node:_http_outgoing:652:11)
    at setCookie (file:///workspace/bcg-monorepo/node_modules/.pnpm/h3@1.10.1/node_modules/h3/dist/index.mjs:610:18)
    at updateSession (file:///workspace/bcg-monorepo/node_modules/.pnpm/h3@1.10.1/node_modules/h3/dist/index.mjs:1309:5)
    at async Object.update (file:///workspace/bcg-monorepo/node_modules/.pnpm/h3@1.10.1/node_modules/h3/dist/index.mjs:1245:7)
    at async updateSession (/workspace/bcg-monorepo/apps/solid-session-example/src/routes/index.tsx?pick=route:13:5) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
```

A simple example of `index.ts`

```typescript
Even a simple example fails:

```typescript
import { Title } from "@solidjs/meta";
import { useSession } from "vinxi/http";
import { RouteDefinition } from "@solidjs/router";
import Counter from "~/components/Counter";

function getSession() {
  return useSession({
    password:
      process.env.SESSION_SECRET ?? "areallylongsecretthatyoushouldreplace",
  });
}

async function updateSession() {
  try {
    const session = await getSession();
    await session.update((d) => (d.userId = "example-user-id"));
  } catch (err) {
    console.error(err);
  }
}

export const route = {
  load: () => updateSession(),
} satisfies RouteDefinition;

export default function Home() {
  return (
    <main>
      <Title>Hello World</Title>
      <h1>Hello world!</h1>
      <Counter />
      <p>
        Visit{" "}
        <a href="https://start.solidjs.com" target="_blank">
          start.solidjs.com
        </a>{" "}
        to learn how to build SolidStart apps.
      </p>
    </main>
  );
}
```

**Comment by nksaraf** [comment]
I think the issue here is (and @ryansolid can correct me), is that if you call updateSession in a `load` function, that usually runs after the initial shell has started streaming (thus the headers have also been sent). You should typically updateSession in a middleware. (@ryansolid do we have an example)

**Comment by ryansolid** [comment]
It's quite likely here. The reason is that there is no resource being waited on so it streams off right away. My example in the repo has the session in the getUser call, but the `getUser` call is in a deferred resource. We need to probably have examples that better reflect best practices here. Because even turning streaming off in the above would still have this this issue because rendering would finish before the updateSession would complete.

**Comment by semiautomatix** [comment]
@nksaraf @ryansolid I appreciate the feedback. This example was somewhat simplied to provide the error. In actuality I was attempting to set the session once receiving the token in an Auth.js callback, a similar principle to example code. I would need to confirm where in the flow these callbacks occur (that themselves are a result of a callback request from Auth0).

**Comment by semiautomatix** [comment]
Thank for the headsup on the middleware, it was perfect for requirements. However note (and I've now inserted a try-catch) that the entire server is crashing everytime I do a refresh in the browser.

middleware.ts:

```typescript
export default createMiddleware({
  onRequest: [
    async (event) => {
      console.log("REQUEST", event.request.url);
      const { request } = event;
      // if the userSession exists then set the userId in solid-start server session
      const userSession = await getSession(request, authOpts);
      if (userSession) {
        try {
          const session = await useSession({
            password: process.env.SESSION_SECRET ?? "",
          });
          session.update((d: any) => (d.userId = userSession.user?.id ?? ""));
        } catch (err) {
          // Error: Cannot set headers after they are sent to the client
          console.warn(err);
        }
      }
    },
  ],
  onBeforeResponse: [
    (event, { body }) => {
      console.log("BEFORE RESPONSE", body);
    },
  ],
});
```

CTRL-F5 (it's a dev environment, sometimes this is the only option): 

`GET http://localhost:3000/home/cards?page=1 net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)`

```
REQUEST http://localhost:3000/home/cards?page=1
BEFORE RESPONSE ReadableStream { locked: false, state: 'readable', supportsBYOB: false }
REQUEST http://localhost:3000/home/cards?page=1
BEFORE RESPONSE ReadableStream { locked: false, state: 'readable', supportsBYOB: false }
node:_http_outgoing:652
    throw new ERR_HTTP_HEADERS_SENT('set');
          ^

Error: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (node:_http_outgoing:652:11)
    at setCookie (file:///workspace/bcg-monorepo/node_modules/.pnpm/h3@1.10.1/node_modules/h3/dist/index.mjs:610:18)
    at updateSession (file:///workspace/bcg-monorepo/node_modules/.pnpm/h3@1.10.1/node_modules/h3/dist/index.mjs:1309:5)
    at async Object.update (file:///workspace/bcg-monorepo/node_modules/.pnpm/h3@1.10.1/node_modules/h3/dist/index.mjs:1245:7) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
```

**Comment by semiautomatix** [comment]
I've closed this as my particular use case is resolved. However, you may want to investigate amending the documents to provide the information regarding the Solid Start lifecycle and where best to update the session.

**Comment by nksaraf** [comment]
yup this will be documented soon im hoping
