### ISSUE TITLE
raw-imports result in warnings in dev-mode

### ISSUE THREAD

**Issue by indeyets** [nksaraf/vinxi#226]
How to reproduce:

1. create a new project with solid-start 0.6.0
2. create `src/test.ftl` file with arbitrary text contents
3. alter `app.tsx` to have this: `import ftl from './test.ftl?raw';` and output it somewhere using `<pre>{ftl}</pre>`.
4. run project with `npm run dev` and open the page

see this in terminal:

```
Error: Failed to load url /_build/src/test.ftl (resolved id: /_build/src/test.ftl) in /Users/indy/Documents/Sources/_mine/solid-start-raw-import/solid-start-raw-import/src/test.ftl. Does the file exist?
    at loadAndTransform (file:///Users/indy/Documents/Sources/_mine/solid-start-raw-import/solid-start-raw-import/node_modules/.pnpm/vite@5.1.1/node_modules/vite/dist/node/chunks/dep-94_H5fT6.js:53582:21)
    at async getViteModuleNode (file:///Users/indy/Documents/Sources/_mine/solid-start-raw-import/solid-start-raw-import/node_modules/.pnpm/vinxi@0.3.4_preact@10.19.6/node_modules/vinxi/lib/manifest/collect-styles.js:54:4)
    at async add_by_url (file:///Users/indy/Documents/Sources/_mine/solid-start-raw-import/solid-start-raw-import/node_modules/.pnpm/vinxi@0.3.4_preact@10.19.6/node_modules/vinxi/lib/manifest/collect-styles.js:86:16)
    at async Promise.all (index 0)
    at async findDeps (file:///Users/indy/Documents/Sources/_mine/solid-start-raw-import/solid-start-raw-import/node_modules/.pnpm/vinxi@0.3.4_preact@10.19.6/node_modules/vinxi/lib/manifest/collect-styles.js:112:2)
    at async add (file:///Users/indy/Documents/Sources/_mine/solid-start-raw-import/solid-start-raw-import/node_modules/.pnpm/vinxi@0.3.4_preact@10.19.6/node_modules/vinxi/lib/manifest/collect-styles.js:81:4)
    at async add_by_url (file:///Users/indy/Documents/Sources/_mine/solid-start-raw-import/solid-start-raw-import/node_modules/.pnpm/vinxi@0.3.4_preact@10.19.6/node_modules/vinxi/lib/manifest/collect-styles.js:89:4)
    at async Promise.all (index 6)
    at async findDeps (file:///Users/indy/Documents/Sources/_mine/solid-start-raw-import/solid-start-raw-import/node_modules/.pnpm/vinxi@0.3.4_preact@10.19.6/node_modules/vinxi/lib/manifest/collect-styles.js:112:2)
    at async add (file:///Users/indy/Documents/Sources/_mine/solid-start-raw-import/solid-start-raw-import/node_modules/.pnpm/vinxi@0.3.4_preact@10.19.6/node_modules/vinxi/lib/manifest/collect-styles.js:81:4)
    at async add_by_url (file:///Users/indy/Documents/Sources/_mine/solid-start-raw-import/solid-start-raw-import/node_modules/.pnpm/vinxi@0.3.4_preact@10.19.6/node_modules/vinxi/lib/manifest/collect-styles.js:89:4)
    at async Promise.all (index 1)
    at async findDeps (file:///Users/indy/Documents/Sources/_mine/solid-start-raw-import/solid-start-raw-import/node_modules/.pnpm/vinxi@0.3.4_preact@10.19.6/node_modules/vinxi/lib/manifest/collect-styles.js:112:2)
    at async add (file:///Users/indy/Documents/Sources/_mine/solid-start-raw-import/solid-start-raw-import/node_modules/.pnpm/vinxi@0.3.4_preact@10.19.6/node_modules/vinxi/lib/manifest/collect-styles.js:81:4)
    at async add_by_url (file:///Users/indy/Documents/Sources/_mine/solid-start-raw-import/solid-start-raw-import/node_modules/.pnpm/vinxi@0.3.4_preact@10.19.6/node_modules/vinxi/lib/manifest/collect-styles.js:89:4)
    at async Promise.all (index 1)
    at async findDeps (file:///Users/indy/Documents/Sources/_mine/solid-start-raw-import/solid-start-raw-import/node_modules/.pnpm/vinxi@0.3.4_preact@10.19.6/node_modules/vinxi/lib/manifest/collect-styles.js:112:2)
    at async add (file:///Users/indy/Documents/Sources/_mine/solid-start-raw-import/solid-start-raw-import/node_modules/.pnpm/vinxi@0.3.4_preact@10.19.6/node_modules/vinxi/lib/manifest/collect-styles.js:81:4)
    at async add_by_url (file:///Users/indy/Documents/Sources/_mine/solid-start-raw-import/solid-start-raw-import/node_modules/.pnpm/vinxi@0.3.4_preact@10.19.6/node_modules/vinxi/lib/manifest/collect-styles.js:89:4)
    at async Promise.all (index 2)
    at async findDeps (file:///Users/indy/Documents/Sources/_mine/solid-start-raw-import/solid-start-raw-import/node_modules/.pnpm/vinxi@0.3.4_preact@10.19.6/node_modules/vinxi/lib/manifest/collect-styles.js:112:2)
    at async findDependencies (file:///Users/indy/Documents/Sources/_mine/solid-start-raw-import/solid-start-raw-import/node_modules/.pnpm/vinxi@0.3.4_preact@10.19.6/node_modules/vinxi/lib/manifest/collect-styles.js:127:5)
    at async findStylesInModuleGraph (file:///Users/indy/Documents/Sources/_mine/solid-start-raw-import/solid-start-raw-import/node_modules/.pnpm/vinxi@0.3.4_preact@10.19.6/node_modules/vinxi/lib/manifest/collect-styles.js:156:23)
    at async viteAssets (file:///Users/indy/Documents/Sources/_mine/solid-start-raw-import/solid-start-raw-import/node_modules/.pnpm/vinxi@0.3.4_preact@10.19.6/node_modules/vinxi/lib/manifest/dev-server-manifest.js:46:7)
    at async Object.assets (file:///Users/indy/Documents/Sources/_mine/solid-start-raw-import/solid-start-raw-import/node_modules/.pnpm/vinxi@0.3.4_preact@10.19.6/node_modules/vinxi/lib/manifest/dev-server-manifest.js:217:16)
    at async createPageEvent (/Users/indy/Documents/Sources/_mine/solid-start-raw-import/solid-start-raw-import/node_modules/.pnpm/@solidjs+start@0.6.0_solid-js@1.8.15_vinxi@0.3.4_vite@5.1.4/node_modules/@solidjs/start/server/pageEvent.ts:30:17)
    at async eval (/Users/indy/Documents/Sources/_mine/solid-start-raw-import/solid-start-raw-import/node_modules/.pnpm/@solidjs+start@0.6.0_solid-js@1.8.15_vinxi@0.3.4_vite@5.1.4/node_modules/@solidjs/start/server/handler.ts:37:25)
    at async _callHandler (file:///Users/indy/Documents/Sources/_mine/solid-start-raw-import/solid-start-raw-import/node_modules/.pnpm/h3@1.10.1/node_modules/h3/dist/index.mjs:1563:16)
    at async file:///Users/indy/Documents/Sources/_mine/solid-start-raw-import/solid-start-raw-import/node_modules/.pnpm/h3@1.10.1/node_modules/h3/dist/index.mjs:1697:19
    at async Object.callAsync (/Users/indy/Documents/Sources/_mine/solid-start-raw-import/solid-start-raw-import/node_modules/.pnpm/unctx@2.3.1/node_modules/unctx/dist/index.cjs:74:16)
    at async Server.toNodeHandle (file:///Users/indy/Documents/Sources/_mine/solid-start-raw-import/solid-start-raw-import/node_modules/.pnpm/h3@1.10.1/node_modules/h3/dist/index.mjs:1907:7) {
  code: 'ERR_LOAD_URL'
```

BUT: it seems like file is still imported correctly and contents is show as part of the page

**Comment by indeyets** [comment]
Repository: https://github.com/indeyets/solid-start-raw-import

**Comment by nksaraf** [comment]
Yeah i think this warning is part of the asset precrawl. Its not typically an issue, but yeah we should do something about the warning
