### ISSUE TITLE
preset: `static` has been broken since 0.3.5

### ISSUE THREAD

**Issue by birkskyum** [nksaraf/vinxi#227]
- open solid-start basic example.
- change app.config to:

```sh
import { defineConfig } from "@solidjs/start/config";

export default defineConfig({
  ssr: true,
  server: {
    
    prerender: {
      crawlLinks: true
    },
    preset: 'static'
  }
});
```

- build

```sh
┌───────────────────────────────────┐
│ ⚙  Preparing app for static...    │
└───────────────────────────────────┘
✔ Generated public .output/public                                                                                    vinxi 1:31:02 AM
ℹ Initializing prerenderer                                                                                           vinxi 1:31:02 AM
ℹ Building Nitro Server (preset: nitro-prerender)                                                                    vinxi 1:31:02 AM
✔ Nitro Server built                                                                                                 vinxi 1:31:02 AM
✔ You can preview this build using npx serve .output/public                                                          vinxi 1:31:02 AM

 ERROR  Should be provided by compiler                                                                                      1:31:02 AM

  at .vinxi/prerender/index.mjs:2780:7
  at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
  at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
  at async prerender (/Users/admin/repos/solid-start/node_modules/.pnpm/nitropack@2.9.1/node_modules/nitropack/dist/chunks/prerender.mjs:57:26)
  at async createBuild (/Users/admin/repos/solid-start/node_modules/.pnpm/vinxi@0.3.5_debug@4.3.4_preact@10.19.3/node_modules/vinxi/lib/build.js:311:2)
  at async Object.run (/Users/admin/repos/solid-start/node_modules/.pnpm/vinxi@0.3.5_debug@4.3.4_preact@10.19.3/node_modules/vinxi/bin/cli.mjs:225:5)
  at async runCommand (/Users/admin/repos/solid-start/node_modules/.pnpm/citty@0.1.6/node_modules/citty/dist/index.mjs:316:16)
  at async runCommand (/Users/admin/repos/solid-start/node_modules/.pnpm/citty@0.1.6/node_modules/citty/dist/index.mjs:307:11)
  at async runMain (/Users/admin/repos/solid-start/node_modules/.pnpm/citty@0.1.6/node_modules/citty/dist/index.mjs:445:7) 



 ERROR  Should be provided by compiler                                                                                      1:31:02 AM

 ELIFECYCLE  Command failed with exit code 1.
```

the build would complete without error up to and including vinxi 0.3.4

**Comment by nksaraf** [comment]
I tried this build with vinxi 0.3.8, works fine. Can you check again and see if the errors persists with 0.3.8

**Comment by nksaraf** [comment]
This kind of errors sometimes happens if there is multiple versions of vinxi in your project (maybe in the pnpm directory). But this looks like you are using vinxi 0.3.5, give 0.3.8 a try and get back to me

**Comment by birkskyum** [comment]
You're right, if I do clone an example with `pnpm create solid`, it works fine, so it's only if I try to run the examples directly from the solid-start repo, even if i bump vinxi both inside the example and in repo root.
