### ISSUE TITLE
The requested module 'seroval' does not provide an export named 'createPlugin'

### ISSUE THREAD

**Issue by birkskyum** [nksaraf/vinxi#273]
I tried to start a production build made with vinxi 0.3.11 and got this:

```
vinxi start --port 3003
[error] The requested module 'seroval' does not provide an export named 'createPlugin'
  import { createPlugin, createStream, fromJSON, crossSerializeStream, getCrossReferenceHeader } from 'seroval';
  ^^^^^^^^^^^^
  SyntaxError: The requested module 'seroval' does not provide an export named 'createPlugin'
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:134:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:217:5)
  at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
  at async Object.run (node_modules/.pnpm/vinxi@0.3.11_@types+node@20.12.5/node_modules/vinxi/bin/cli.mjs:270:7)
  at async runCommand (node_modules/.pnpm/citty@0.1.6/node_modules/citty/dist/index.mjs:316:16)
  at async runCommand (node_modules/.pnpm/citty@0.1.6/node_modules/citty/dist/index.mjs:307:11)
  at async runMain (node_modules/.pnpm/citty@0.1.6/node_modules/citty/dist/index.mjs:445:7) 
[error] The requested module 'seroval' does not provide an export named 'createPlugin'
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by birkskyum** [comment]
@lxsmnsyc , can you confirm if a createPlugin is supposed to exist?

**Comment by birkskyum** [comment]
It's been a while since I've hit this. Will reopen with proper repro if it resurfaces.
