### ISSUE TITLE
exporting a `class` from `"use server"` results in a compile error.

### ISSUE THREAD

**Issue by indietyp** [nksaraf/vinxi#306]
Exporting a `class` from a file using the `use server` directive results in an error, simple reproductive case:

```js
"use server";

export class Example {}
```

The error:

```log
Error: undefined does not match field "params": [Pattern] of type FunctionExpression
    at addParam (<REDACTED>/node_modules/ast-types/lib/types.js:455:27)
    at <REDACTED>/node_modules/ast-types/lib/types.js:505:25
    at Array.forEach (<anonymous>)
    at builder.from (<REDACTED>/node_modules/ast-types/lib/types.js:503:46)
    at wrapExports (file://<REDACTED>node_modules/@vinxi/plugin-directives/plugins/wrap-exports.js:393:45)
    at Object.transform (file://<REDACTED>/node_modules/@vinxi/plugin-directives/plugins/wrap-exports.js:44:24)
    at TransformContext.transform (file:///<REDACTED>/node_modules/@vinxi/plugin-directives/plugin.js:52:31)
    at Object.transform (file://<REDACTED>/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:51139:62)
    at async loadAndTransform (file://<REDACTED>/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:53894:29)
    at async instantiateModule (file://<REDACTED>/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:54954:10)
```

**Comment by ryansolid** [comment]
This isn't the intended use. "use server" boundary is just for function RPCs you shouldn't be exporting anything else from it.
