### ISSUE TITLE
vinxi build --config <path> broken in 0.4.3

### ISSUE THREAD

**Issue by paularmstrong** [nksaraf/vinxi#388]
This worked fine in 0.4.1:

```sh
vinxi build --config ./config/app.config.ts
```

After upgrading to 0.4.3:

```sh
vinxi build --config ./config/app.config.ts

vinxi v0.4.3


⚙  Building your app...
vinxi v0.4.3

 ERROR  Couldn't load app                                                                 8:37:10 AM

  at Object.run (web/node_modules/vinxi/bin/cli.mjs:231:12)
  at async runCommand (web/node_modules/citty/dist/index.mjs:316:16)
  at async runCommand (web/node_modules/citty/dist/index.mjs:307:11)
  at async runMain (web/node_modules/citty/dist/index.mjs:445:7)



 ERROR  Couldn't load app                                                                 8:37:10 AM


 ERROR  Exited with code: 1                                                               8:37:10 AM

  at CommandChild.pipedStdoutBuffer (web/node_modules/dax-sh/esm/mod.js:9392:19)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Vinxi will only build if the config is in the same directory as the CWD.

**Comment by nksaraf** [comment]
Okay sounds like a bug .. I'll try to take a look in this week

**Comment by remi-espie** [comment]
Hello, I'm facing the same issue and no updates here. Does a workaround have been found ? Thanks

**Comment by hennessyevan** [comment]
I'm not sure what changed, `0.5.0` doesn't work either

**Comment by nksaraf** [comment]
Heyy my bad the fix for this is not in, if anyone's got the time, the fix should be simple, a PR would be very welcome. Otherwise I'll try to get to it this week
