### ISSUE TITLE
Vinxi's build command tries to run node.EXE even when using Deno

### ISSUE THREAD

**Issue by Ciantic** [nksaraf/vinxi#407]
I have example repo here:

https://github.com/Ciantic/deno-solid-test/

Some reason when running it through *deno* it still tries to run `node.exe` instances.

Notice the telltale warning:

> (Use `node.EXE --trace-warnings ...` to show where the warning was created)

In following call:

```shell
$ deno run -A build 

⚙  Building your app...
vinxi v0.4.3
(node:33840) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node.EXE --trace-warnings ...` to show where the warning was created)
ReferenceError: Deno is not defined
    at file:///C:/Source/JavaScript/solid-start-test/deno-solid-test/node_modules/.deno/@jsr+std__fs@0.221.0/node_modules/@jsr/std__fs/ensure_symlink.js:7:19
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadFile (file:///C:/Source/JavaScript/solid-start-test/deno-solid-test/node_modules/.deno/vinxi@0.4.3/node_modules/vinxi/lib/load-app.js:83:25)
    at async loadApp (file:///C:/Source/JavaScript/solid-start-test/deno-solid-test/node_modules/.deno/vinxi@0.4.3/node_modules/vinxi/lib/load-app.js:137:19)
    at async Object.run (file:///C:/Source/JavaScript/solid-start-test/deno-solid-test/node_modules/.deno/vinxi@0.4.3/node_modules/vinxi/bin/cli.mjs:229:17)
    at async runCommand (file:///C:/Source/JavaScript/solid-start-test/deno-solid-test/node_modules/.deno/citty@0.1.6/node_modules/citty/dist/index.mjs:316:16)
    at async runCommand (file:///C:/Source/JavaScript/solid-start-test/deno-solid-test/node_modules/.deno/citty@0.1.6/node_modules/citty/dist/index.mjs:307:11)
    at async runMain (file:///C:/Source/JavaScript/solid-start-test/deno-solid-test/node_modules/.deno/citty@0.1.6/node_modules/citty/dist/index.mjs:445:7)

```

**Comment by Ciantic** [comment]
Nitro does have deno support with preset `deno_server`, but Vinxi is not aware of that:

https://github.com/nksaraf/vinxi/blob/432fdf559bdd41c5d0c06f6b4039dd8738638c3c/packages/vinxi/bin/cli.mjs#L325-L351
