### ISSUE TITLE
SolidJS basic SSR example is broken

### ISSUE THREAD

**Issue by msteen** [nksaraf/vinxi#42]
The [basic SSR example for SolidJS](https://stackblitz.com/github/nksaraf/vinxi/tree/main/examples/solid/ssr/basic) builds with various warnings then when a request is made to server it throws an exception about React not being found, causing a 500 error response.

Relevant warning (the rest are the same):
```
[vite] warning: The JSX import source cannot be set without also enabling React's "automatic" JSX transform
1  |  /** @jsxImportSource solid-js */
   |                       ^
2  |  import { Link, Style, useHead } from "@solidjs/meta";
3  |  import { splitProps } from "solid-js";

  Plugin: vite:esbuild
  File: node_modules/.pnpm/@vinxi+solid@0.0.14/node_modules/@vinxi/solid/render-asset.jsx
```

The 500 error after making a request:
```
[h3] [unhandled] ReferenceError: React is not defined
    at eval (app/server.tsx:22:83)
    ... 5 lines matching cause stack trace ...
    at async Server.toNodeHandle (file://node_modules/.pnpm/h3@1.9.0/node_modules/h3/dist/index.mjs:1885:7) {
  cause: ReferenceError: React is not defined
      at eval (app/server.tsx:22:83)
      at file://node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/web/dist/server.js:262:34
      at createRoot (file://node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:58:14)
      at Proxy.renderToStream (file://node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/web/dist/server.js:260:14)
      at eval (app/server.tsx:22:40)
      at async Object.handler (file://node_modules/.pnpm/h3@1.9.0/node_modules/h3/dist/index.mjs:1675:19)
      at async Server.toNodeHandle (file://node_modules/.pnpm/h3@1.9.0/node_modules/h3/dist/index.mjs:1885:7),
  statusCode: 500,
  fatal: false,
  unhandled: true,
  statusMessage: undefined,
  data: undefined
}
```

**Comment by nksaraf** [comment]
Thanks for catching this. Fixed in fcc469358b3063cff8da6221224f9dec9f4f2feb
