### ISSUE TITLE
defaultServerConditions is not iterable

### ISSUE THREAD

**Issue by birkskyum** [nksaraf/vinxi#435]
This is hit in
- #424 

It also seems possible to hit with vinxi 0.5.1 from solid-start. More details might come.

**Comment by katywings** [comment]
Also getting this with solid-start 1.0.10 + vinxi 0.5.1 + vite 5.4.11

**Comment by Marvin-Brouwer** [comment]
@katywings you are a lifesaver.
For some extra context, this also happens with `vite@^6` and `vite-plugin-solid@^2.11.0`. So, it's likely not a `vinxi` issue.

**Comment by birkskyum** [comment]
@Marvin-Brouwer does that repro in stackblitz

**Comment by Marvin-Brouwer** [comment]
@birkskyum sorry for the late reply, I haven't been able to respond due to personal situation.
I had a quick look, but I couldn't reproduce it with the solidJS starter template.
https://stackblitz.com/edit/solidjs-templates-bchp1qnq?file=vite.config.ts
I'll have a look this afternoon to see if it's maybe in combination with some of the plugins I use.

**Comment by timothyallan** [comment]
Also getting this after upgrading to 0.5.3

![Image](https://github.com/user-attachments/assets/60661252-9d97-4930-a07d-b74357d33145)

**Comment by birkskyum** [comment]
@timothyallan make sure you have no vite v5 installations

**Comment by Eliot00** [comment]
I can build locally but get errors in cloudflare pages.

<pre class="c_kj c_bv c_jk c_ii c_hz c_ia c_dq c_oj c_ok c_ol c_om c_ha c_hb c_nw c_bx c_on">
20:12:07.174 | 📦 Compiling ssr router...
-- | --
20:12:07.174 | vinxi building router ssr in http mode
20:12:07.446 | [error] defaultServerConditions is not iterable
20:12:07.446 | at configEnvironment (node_modules/.pnpm/vite-plugin-solid@2.11.6_solid-js@1.9.5_vite@5.4.14/node_modules/vite-plugin-solid/dist/esm/index.mjs:133:43)
20:12:07.447 | at async runConfigEnvironmentHook (node_modules/.pnpm/vite@6.2.0/node_modules/vite/dist/node/chunks/dep-ByPKlqZ5.js:54653:19)
20:12:07.447 | at async resolveConfig (node_modules/.pnpm/vite@6.2.0/node_modules/vite/dist/node/chunks/dep-ByPKlqZ5.js:54038:3)
20:12:07.447 | at async createBuilder (node_modules/.pnpm/vite@6.2.0/node_modules/vite/dist/node/chunks/dep-ByPKlqZ5.js:51930:18)
20:12:07.447 | at async Module.build (node_modules/.pnpm/vite@6.2.0/node_modules/vite/dist/node/chunks/dep-ByPKlqZ5.js:51219:19)
20:12:07.447 | at async createViteBuild (node_modules/.pnpm/vinxi@0.5.3_typescript@5.8.2/node_modules/vinxi/lib/build.js:395:17)
20:12:07.447 | at async createRouterBuild (node_modules/.pnpm/vinxi@0.5.3_typescript@5.8.2/node_modules/vinxi/lib/build.js:529:2)
20:12:07.447 | at async node_modules/.pnpm/vinxi@0.5.3_typescript@5.8.2/node_modules/vinxi/lib/build.js:59:5
20:12:07.447 | at async createBuild (node_modules/.pnpm/vinxi@0.5.3_typescript@5.8.2/node_modules/vinxi/lib/build.js:58:4)
20:12:07.447 | at async Object.run (node_modules/.pnpm/vinxi@0.5.3_typescript@5.8.2/node_modules/vinxi/bin/cli.mjs:235:5)
20:12:07.448 | at async runCommand (node_modules/.pnpm/citty@0.1.6/node_modules/citty/dist/index.mjs:316:16)
20:12:07.448 | at async runCommand (node_modules/.pnpm/citty@0.1.6/node_modules/citty/dist/index.mjs:307:11)
20:12:07.448 | at async runMain (node_modules/.pnpm/citty@0.1.6/node_modules/citty/dist/index.mjs:445:7)
20:12:07.448 |  
20:12:07.448 | [error] defaultServerConditions is not iterable
20:12:07.457 | [error] Exited with code: 1
20:12:07.457 | at CommandChild.pipedStdoutBuffer (node_modules/.pnpm/dax-sh@0.39.2/node_modules/dax-sh/esm/mod.js:9392:19)
20:12:07.457 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
20:12:07.457 |  
20:12:07.458 | [error] Exited with code: 1
20:12:07.469 | ELIFECYCLE  Command failed with exit code 1.
20:12:07.498 | Failed: Error while executing user command. Exited with error code: 1
20:12:07.508 | Failed: build command exited with code: 1
20:12:08.309 | Failed: error occurred while running build command

</pre>

**Comment by birkskyum** [comment]
@Eliot00 , notice the "vite@5.4.14" in the output you shared - that's the issue. There is a vite 5 installation.

You can try to delete and recreate your lockfile, or explicit add  vite 6 to the list of dependencies, or depending on which package manager you use, add vite 6 to the overrides / resolutions to force use of vite 6

**Comment by Eliot00** [comment]
@birkskyum Thank you for your response. I just managed to deploy successfully by building locally and uploading the assets without making any changes to the code. I'm not sure why the Cloudflare Github automatic integration deployment method is throwing an error. I'll try upgrading Vite later to see if that resolves the issue.

**Comment by birkskyum** [comment]
Excellent! It could be a cache somewhere causing problems.

**Comment by AlexErrant** [comment]
Hah yeah I forgot to update vinxi and Birk's advice fixed it - thanks!
